apiVersion: v1
kind: Secret
metadata:
  name: clawworld-secrets
  namespace: clawworld
type: Opaque
stringData:
  DB_PASSWORD: "clawpass"
  MQ_PASSWORD: "clawpass"
  LLM_API_KEY: "sk-uX8hVbhIM27Xt4iJE84b79900eAa4931B0122034Bb092510"
